# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('linecount', models.IntegerField()),
                ('slotcount', models.IntegerField()),
                ('slotduration', models.IntegerField()),
                ('max_slots', models.IntegerField(default=0, help_text='0 for unlimited')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Dock',
                'verbose_name_plural': 'Docks',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('payload', models.PositiveSmallIntegerField(choices=[(1, b'1 t'), (2, b'2 t'), (3, b'3 t'), (4, b'4 t'), (5, b'5 t'), (6, b'6 t'), (7, b'7 t'), (8, b'8 t'), (9, b'9 t'), (10, b'10 t'), (11, b'11 t'), (12, b'12 t'), (13, b'13 t'), (14, b'14 t'), (15, b'15 t'), (16, b'16 t'), (17, b'17 t'), (18, b'18 t'), (19, b'19 t'), (20, b'20 t'), (21, b'21 t'), (22, b'22 t'), (23, b'23 t'), (24, b'24 t'), (25, b'25 t'), (26, b'26 t'), (27, b'27 t'), (28, b'28 t'), (29, b'29 t'), (30, b'30 t'), (31, b'31 t'), (32, b'32 t'), (33, b'33 t'), (34, b'34 t'), (35, b'35 t'), (36, b'36 t'), (37, b'37 t'), (38, b'38 t'), (39, b'39 t'), (40, b'40 t')], default=25)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(editable=False)),
                ('host', models.CharField(blank=True, max_length=40)),
                ('task', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logging',
                'verbose_name_plural': 'Loggings',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeslot', models.IntegerField()),
                ('line', models.IntegerField()),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_klv', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslots.Block')),
            ],
            options={
                'ordering': ['date', 'timeslot', 'line'],
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortdescription', models.CharField(blank=True, max_length=200)),
                ('longdescription', models.TextField(blank=True)),
                ('booking_deadline', models.TimeField(help_text='Booking deadline = time on the day before from which on a slot can not be reserved any more. Set this to midnight to turn off this feature completely for this station')),
                ('rnvp', models.TimeField(help_text='RVNP = Rien ne vas plus -- time when a slot can not be edited any more, set to Midnight to have the deadline as RNVP')),
                ('opened_on_weekend', models.BooleanField(default=False, help_text='Choose this option if this station will be opened on weekends')),
                ('multiple_charges', models.BooleanField(default=True, help_text='If this option is marked, the reservation form offers the opportunity to add more than one job')),
                ('has_status', models.BooleanField(default=False, help_text='This option adds a Statusbar to the job view, which shows the current loading status')),
                ('has_klv', models.BooleanField(default=False, help_text='Choose this option if you want to be able to mark charges with an KLV/NV flag')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default=b'de', max_length=2, verbose_name='Language')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Street')),
                ('country', models.CharField(blank=True, max_length=200, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Phone')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('ZIP', models.CharField(blank=True, max_length=20, verbose_name='ZIP')),
                ('town', models.CharField(blank=True, max_length=200, verbose_name='Town')),
                ('stations', models.ManyToManyField(to='timeslots.Station')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslots.UserProfile'),
        ),
        migrations.AddField(
            model_name='job',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslots.Slot'),
        ),
        migrations.AddField(
            model_name='dock',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslots.Station'),
        ),
        migrations.AddField(
            model_name='block',
            name='dock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslots.Dock'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([('date', 'block', 'timeslot', 'line')]),
        ),
    ]
