# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='has_product',
            field=models.BooleanField(default=False, help_text='Choose this option if you want to be able to add information about available products to the docks of this station'),
        ),
    ]
