# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-20 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0003_station_has_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date']},
        ),
    ]
